import { Form, Head } from '@inertiajs/react';
import { REGEXP_ONLY_DIGITS } from 'input-otp';
import {
    KeyRound,
    ShieldCheck,
    ShieldQuestion,
    Sparkles,
} from 'lucide-react';
import { useMemo, useState } from 'react';

import InputError from '@/components/input-error';
import { Button } from '@/components/ui/button';
import { Input } from '@/components/ui/input';
import {
    InputOTP,
    InputOTPGroup,
    InputOTPSlot,
} from '@/components/ui/input-otp';
import { Spinner } from '@/components/ui/spinner';
import { OTP_MAX_LENGTH } from '@/hooks/use-two-factor-auth';
import { store } from '@/routes/two-factor/login';

export default function TwoFactorChallenge() {
    const [showRecoveryInput, setShowRecoveryInput] =
        useState<boolean>(false);

    const [code, setCode] = useState<string>('');

    const authConfigContent = useMemo<{
        title: string;
        description: string;
        toggleText: string;
        badge: string;
    }>(() => {
        if (showRecoveryInput) {
            return {
                title: 'Recovery Code',
                description:
                    'Use one of your emergency recovery codes to access your account securely.',
                toggleText: 'login using an authentication code',
                badge: 'Recovery Mode',
            };
        }

        return {
            title: 'Authentication Code',
            description:
                'Enter the verification code generated by your authenticator application.',
            toggleText: 'login using a recovery code',
            badge: '2FA Protected',
        };
    }, [showRecoveryInput]);

    const toggleRecoveryMode = (clearErrors: () => void): void => {
        setShowRecoveryInput(!showRecoveryInput);

        clearErrors();

        setCode('');
    };

    return (
        <>
            <Head title="Two-Factor Authentication" />

            <main className="relative min-h-screen overflow-hidden bg-background text-foreground">
                <div className="absolute inset-0 bg-gradient-to-br from-primary/[0.08] via-background to-background" />

                <div className="absolute -right-32 -top-32 h-96 w-96 rounded-full bg-primary/10 blur-3xl" />

                <div className="absolute -bottom-32 -left-32 h-96 w-96 rounded-full bg-primary/10 blur-3xl" />

                <div className="relative grid min-h-screen lg:grid-cols-[1fr_560px]">
                    {/* Left Side */}
                    <section className="hidden border-r bg-muted/[0.08] px-10 py-10 lg:flex lg:flex-col lg:justify-between xl:px-16">
                        <div>
                            <div className="flex items-center gap-3">
                                <div className="flex size-12 items-center justify-center rounded-2xl bg-primary text-sm font-bold text-primary-foreground shadow-sm">
                                    JCM
                                </div>

                                <div>
                                    <p className="text-sm font-semibold">
                                        JCM Web Solution
                                    </p>

                                    <p className="mt-1 text-xs text-muted-foreground">
                                        Smart business systems
                                    </p>
                                </div>
                            </div>

                            <div className="mt-24 max-w-2xl">
                                <div className="mb-6 inline-flex items-center gap-2 rounded-full border bg-background/70 px-4 py-2 text-sm text-muted-foreground shadow-sm backdrop-blur">
                                    <Sparkles className="size-4 text-primary" />
                                    Advanced account protection
                                </div>

                                <h1 className="text-5xl font-semibold tracking-tight xl:text-6xl">
                                    Secure your workspace access.
                                </h1>

                                <p className="mt-6 max-w-xl text-base leading-8 text-muted-foreground">
                                    Two-factor authentication adds an extra
                                    layer of protection to your JCM account by
                                    requiring a secure verification code.
                                </p>
                            </div>
                        </div>

                        <div className="grid max-w-3xl gap-4 xl:grid-cols-3">
                            {[
                                'Secure verification',
                                'Protected login access',
                                'Recovery code support',
                            ].map((item) => (
                                <div
                                    key={item}
                                    className="rounded-2xl border bg-background/70 p-4 shadow-sm backdrop-blur"
                                >
                                    <ShieldCheck className="mb-3 size-5 text-primary" />

                                    <p className="text-sm font-medium">
                                        {item}
                                    </p>
                                </div>
                            ))}
                        </div>
                    </section>

                    {/* Right Side */}
                    <section className="flex min-h-screen items-center justify-center px-6 py-10 sm:px-10">
                        <div className="w-full max-w-md">
                            <div className="mb-8">
                                <div className="mb-5 flex size-14 items-center justify-center rounded-2xl bg-primary/10 text-primary ring-1 ring-primary/15">
                                    {showRecoveryInput ? (
                                        <ShieldQuestion className="size-6" />
                                    ) : (
                                        <KeyRound className="size-6" />
                                    )}
                                </div>

                                <div className="space-y-2">
                                    <div className="flex flex-wrap items-center gap-2">
                                        <h2 className="text-3xl font-semibold tracking-tight">
                                            {authConfigContent.title}
                                        </h2>

                                        <span className="rounded-full border border-primary/20 bg-primary/10 px-2 py-0.5 text-[11px] font-medium text-primary">
                                            {authConfigContent.badge}
                                        </span>
                                    </div>

                                    <p className="text-sm leading-6 text-muted-foreground">
                                        {authConfigContent.description}
                                    </p>
                                </div>
                            </div>

                            <Form
                                {...store.form()}
                                className="space-y-5"
                                resetOnError
                                resetOnSuccess={!showRecoveryInput}
                            >
                                {({
                                    errors,
                                    processing,
                                    clearErrors,
                                }) => (
                                    <>
                                        <div className="grid gap-4">
                                            {showRecoveryInput ? (
                                                <div className="grid gap-2">
                                                    <Input
                                                        name="recovery_code"
                                                        type="text"
                                                        placeholder="Enter recovery code"
                                                        autoFocus={
                                                            showRecoveryInput
                                                        }
                                                        required
                                                        className="h-12 rounded-xl border-border/60 shadow-sm"
                                                    />

                                                    <InputError
                                                        message={
                                                            errors.recovery_code
                                                        }
                                                    />
                                                </div>
                                            ) : (
                                                <div className="rounded-2xl border bg-muted/[0.15] px-5 py-6">
                                                    <div className="flex flex-col items-center justify-center space-y-4 text-center">
                                                        <div className="flex w-full items-center justify-center">
                                                            <InputOTP
                                                                name="code"
                                                                maxLength={
                                                                    OTP_MAX_LENGTH
                                                                }
                                                                value={code}
                                                                onChange={(
                                                                    value,
                                                                ) =>
                                                                    setCode(
                                                                        value,
                                                                    )
                                                                }
                                                                disabled={
                                                                    processing
                                                                }
                                                                pattern={
                                                                    REGEXP_ONLY_DIGITS
                                                                }
                                                            >
                                                                <InputOTPGroup>
                                                                    {Array.from(
                                                                        {
                                                                            length:
                                                                                OTP_MAX_LENGTH,
                                                                        },
                                                                        (
                                                                            _,
                                                                            index,
                                                                        ) => (
                                                                            <InputOTPSlot
                                                                                key={
                                                                                    index
                                                                                }
                                                                                index={
                                                                                    index
                                                                                }
                                                                            />
                                                                        ),
                                                                    )}
                                                                </InputOTPGroup>
                                                            </InputOTP>
                                                        </div>

                                                        <p className="text-xs text-muted-foreground">
                                                            Enter the code from
                                                            your authenticator
                                                            app
                                                        </p>

                                                        <InputError
                                                            message={
                                                                errors.code
                                                            }
                                                        />
                                                    </div>
                                                </div>
                                            )}

                                            <Button
                                                type="submit"
                                                className="mt-2 h-12 w-full rounded-xl text-sm font-semibold shadow-sm"
                                                disabled={processing}
                                            >
                                                {processing ? (
                                                    <>
                                                        <Spinner />
                                                        Verifying...
                                                    </>
                                                ) : (
                                                    <>
                                                        Continue
                                                    </>
                                                )}
                                            </Button>
                                        </div>

                                        <div className="border-t pt-5 text-center text-sm text-muted-foreground">
                                            <span>Or you can </span>

                                            <button
                                                type="button"
                                                className="font-semibold text-primary transition-opacity hover:opacity-80"
                                                onClick={() =>
                                                    toggleRecoveryMode(
                                                        clearErrors,
                                                    )
                                                }
                                            >
                                                {
                                                    authConfigContent.toggleText
                                                }
                                            </button>
                                        </div>
                                    </>
                                )}
                            </Form>

                            <div className="mt-6 rounded-2xl border border-primary/10 bg-primary/[0.03] p-4">
                                <div className="flex items-start gap-3">
                                    <div className="mt-0.5 flex size-9 shrink-0 items-center justify-center rounded-xl bg-primary/10 text-primary">
                                        <Sparkles className="size-4" />
                                    </div>

                                    <div>
                                        <h3 className="text-sm font-semibold text-foreground">
                                            Secure Verification
                                        </h3>

                                        <p className="mt-1 text-sm leading-6 text-muted-foreground">
                                            Your verification codes are securely
                                            validated to protect your account
                                            and workspace access.
                                        </p>
                                    </div>
                                </div>
                            </div>
                        </div>
                    </section>
                </div>
            </main>
        </>
    );
}