import InputError from '@/components/input-error';
import { PageHero } from '@/components/admin-ui/page-hero';
import { SectionCard } from '@/components/admin-ui/section-card';
import { Button } from '@/components/ui/button';
import { Input } from '@/components/ui/input';
import { Label } from '@/components/ui/label';
import AppLayout from '@/layouts/app-layout';
import { type BreadcrumbItem } from '@/types';
import { Head, useForm } from '@inertiajs/react';
import { Building2, Database, UserPlus } from 'lucide-react';
import type { FormEvent } from 'react';

type Product={id:number;product_code:string;name:string;status:string}; type Plan={id:number;product_id:number;plan_name:string;billing_interval:string;price:number}; type User={id:number;name:string;email:string}; type Log={id:number;owner_name?:string;owner_email?:string;product_name?:string;plan_name?:string;status:string;business_name:string;created_at:string};
type Props={products:Product[];plans:Plan[];users:User[];logs:Log[]};
const breadcrumbs:BreadcrumbItem[]=[{title:'Systems',href:'/admin/systems'},{title:'Provision Account',href:'/admin/systems/provision'}];
export default function Provision({products,plans,users,logs}:Props){
 const form=useForm({existing_user_id:'',name:'',email:'',password:'',password_confirmation:'',product_id:String(products[0]?.id??''),plan_id:'',billing_interval:'monthly',subscription_status:'active',business_name:'',business_category:'',contact_email:'',contact_phone:'',address_line:'',branch_name:'Main Branch',warehouse_name:'Main Warehouse',notes:''});
 const filtered=plans.filter(p=>String(p.product_id)===form.data.product_id);
 const submit=(e:FormEvent)=>{e.preventDefault();form.post('/admin/systems/provision',{preserveScroll:true});};
 return <AppLayout breadcrumbs={breadcrumbs}><Head title="Provision Account"/><div className="space-y-5"><PageHero eyebrow="Systems Provisioner" title="Provision a complete system account" description="Create or select an account owner, activate a plan, assign owner access, and prepare the operational environment in one workflow."/>
 <form onSubmit={submit} className="grid gap-5 xl:grid-cols-[minmax(0,1fr)_360px]">
  <div className="space-y-5">
   <SectionCard title="Account owner" description="Select an existing client or leave it blank to create a new account."><div className="grid gap-4 md:grid-cols-2"><Field label="Existing client"><select className="h-10 w-full rounded-md border border-input bg-background px-3 text-xs" value={form.data.existing_user_id} onChange={e=>form.setData('existing_user_id',e.target.value)}><option value="">Create new account</option>{users.map(u=><option key={u.id} value={u.id}>{u.name} — {u.email}</option>)}</select></Field><div/>{!form.data.existing_user_id&&<><Field label="Full name"><Input value={form.data.name} onChange={e=>form.setData('name',e.target.value)}/><InputError message={form.errors.name}/></Field><Field label="Email"><Input type="email" value={form.data.email} onChange={e=>form.setData('email',e.target.value)}/><InputError message={form.errors.email}/></Field><Field label="Temporary password"><Input type="password" value={form.data.password} onChange={e=>form.setData('password',e.target.value)}/><InputError message={form.errors.password}/></Field><Field label="Confirm password"><Input type="password" value={form.data.password_confirmation} onChange={e=>form.setData('password_confirmation',e.target.value)}/></Field></>}</div></SectionCard>
   <SectionCard title="System & subscription"><div className="grid gap-4 md:grid-cols-2"><Field label="System"><select className="h-10 w-full rounded-md border border-input bg-background px-3 text-xs" value={form.data.product_id} onChange={e=>{form.setData('product_id',e.target.value);form.setData('plan_id','')}}>{products.map(p=><option key={p.id} value={p.id}>{p.name} ({p.status})</option>)}</select></Field><Field label="Plan"><select className="h-10 w-full rounded-md border border-input bg-background px-3 text-xs" value={form.data.plan_id} onChange={e=>form.setData('plan_id',e.target.value)}><option value="">Select plan</option>{filtered.map(p=><option key={p.id} value={p.id}>{p.plan_name} — ₱{Number(p.price).toLocaleString()}</option>)}</select><InputError message={form.errors.plan_id}/></Field><Field label="Billing cycle"><select className="h-10 w-full rounded-md border border-input bg-background px-3 text-xs" value={form.data.billing_interval} onChange={e=>form.setData('billing_interval',e.target.value)}><option value="monthly">Monthly</option><option value="quarterly">Quarterly</option><option value="yearly">Yearly</option><option value="custom">Custom/default</option></select></Field><Field label="Starting status"><select className="h-10 w-full rounded-md border border-input bg-background px-3 text-xs" value={form.data.subscription_status} onChange={e=>form.setData('subscription_status',e.target.value)}><option value="active">Active</option><option value="trial">Trial</option><option value="pending">Pending</option></select></Field></div></SectionCard>
   <SectionCard title="Business & default environment"><div className="grid gap-4 md:grid-cols-2"><Field label="Business name"><Input value={form.data.business_name} onChange={e=>form.setData('business_name',e.target.value)}/><InputError message={form.errors.business_name}/></Field><Field label="Business category"><Input value={form.data.business_category} onChange={e=>form.setData('business_category',e.target.value)}/></Field><Field label="Contact email"><Input value={form.data.contact_email} onChange={e=>form.setData('contact_email',e.target.value)}/></Field><Field label="Contact phone"><Input value={form.data.contact_phone} onChange={e=>form.setData('contact_phone',e.target.value)}/></Field><Field label="Address"><Input value={form.data.address_line} onChange={e=>form.setData('address_line',e.target.value)}/></Field><div/><Field label="Default branch"><Input value={form.data.branch_name} onChange={e=>form.setData('branch_name',e.target.value)}/></Field><Field label="Default warehouse/location"><Input value={form.data.warehouse_name} onChange={e=>form.setData('warehouse_name',e.target.value)}/></Field></div></SectionCard>
  </div>
  <div className="space-y-5"><SectionCard title="Provisioning summary"><div className="space-y-3 text-xs"><Summary icon={<UserPlus className="size-4"/>} text="Account and canonical platform role"/><Summary icon={<Building2 className="size-4"/>} text="Business profile, plan, and subscription"/><Summary icon={<Database className="size-4"/>} text="Product access and operational scopes"/><p className="rounded-xl border border-primary/20 bg-primary/5 p-3 text-muted-foreground">JCM Inventory additionally receives a main branch and main warehouse in <b>jcm_inventory_db</b>.</p><Button className="w-full" disabled={form.processing||!form.data.plan_id}><UserPlus className="size-4"/>{form.processing?'Provisioning...':'Provision account'}</Button></div></SectionCard>
  <SectionCard title="Recent provisioning"><div className="space-y-2">{logs.length===0&&<p className="text-xs text-muted-foreground">No provisioning history yet.</p>}{logs.map(log=><div key={log.id} className="rounded-xl border border-border/60 p-3"><div className="flex justify-between gap-2"><b className="text-xs">{log.business_name}</b><span className="text-[9px] uppercase text-primary">{log.status}</span></div><p className="mt-1 text-[10px] text-muted-foreground">{log.product_name} · {log.plan_name}</p><p className="text-[10px] text-muted-foreground">{log.owner_name} · {log.owner_email}</p></div>)}</div></SectionCard></div>
 </form></div></AppLayout>;
}
function Field({label,children}:{label:string;children:React.ReactNode}){return <div className="space-y-2"><Label className="text-xs">{label}</Label>{children}</div>}
function Summary({icon,text}:{icon:React.ReactNode;text:string}){return <div className="flex items-center gap-3 rounded-xl border border-border/60 p-3"><span className="text-primary">{icon}</span><span>{text}</span></div>}
